# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.a.strova.dk
title: Amalie Stokholm
email: a@strova.dk
author: Amalie Stokholm
description: > # "Amalie Stokholm's Personal Webpage"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: envelope-o
    title: email
    url: mailto:a+wp@strova.dk
  - icon: github
    title: github
    url: https://github.com/amaliestokholm
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/amaliestokholm
  - icon: gitlab
    title: gitlab
    url: https://gitlab.com/amaliestokholm
  - icon: file-pdf-o
    title: resume
    url: https://a.strova.dk/rsc/resume.pdf

counter:
  - title: years studying
    duration: 400
    count: 6
  - title: stars analyzed
    duration: 2000
    count: 40000
    prefix: '~'
